#!/bin/bash

function DisplayDatabases
{
    echo "___________________________________________";
    echo "Your Databases List: "
    index=1;
    dirList=(`ls Databases`)
    echo ${#dirList[@]}
    if [ ${#dirList[@]} != 0 ]
    then
        for i in ${dirList[@]}
        do 
            echo "("$index")" $i
            let index+=1;
        done
    else
        echo "System is Empty!";
    fi
    echo "___________________________________________"; 
}

function CreateDatabase
{
    found=0;
    flag=0;
    echo "Enter Name of Database:"
    read DBname;
    while [ $flag == 0 ]
    do 
        for i in `ls Databases`
        do 
            if [ $i == $DBname ]
            then
                found=1;
                break;
            else  
                found=0;
            fi 
        done

        if [ $found == 1 ]
        then 
            echo $DBname "is already exist , Re-enter the Name: "
            read DBname;
            flag=0;
        else 
            cd Databases
            mkdir $DBname;
            echo "Database Created Successfully..."
            flag=1;
            cd ..
        fi
    done
    
}

function ConnectToDatabase
{
    cd Databases
    flag=0;
    found=0;
    echo "Enter Name of Database: "
    read DBname;
    while [ $flag == 0 ]
    do
        for i in `ls`
        do 
            if [ $i == $DBname ]
            then
                found=1;
                break;
            else
                found=0;
            fi    
        done

        if [ $found == 1 ]
        then
            cd $DBname;
            echo "Connected Successfully...";
            echo "------------------------ "$DBname "Database ------------------------"
            TableMenu
            flag=1;
        else
            echo $DBname "Not found.. Please Re-enter the Database Name: ";
            read DBname;
            flag=0;
        fi
    done
}

function DisplayTables
{
    echo "___________________________________________";
    echo "Your Table List: "
    index=1;
    tableList=(`ls`)
    #echo ${#tableList[@]}
    if [ ${#tableList[@]} != 0 ]
    then 
        for i in `ls *data`
        do 
        
            echo "("$index")" $i | cut -f1 -d".";
            let index+=1;
        done
    else
        echo "This Database is Empty!";
    fi    
    echo "___________________________________________"; 
}

#----> function to Creat Meta-Data(INFo) of Table <----#
function TableMetaData
{
    touch $1.metaData
    echo "Enter Number Of Fields: "
    read NoOfCol;
    echo "NumberOfCols:"$NoOfCol >> $1.metaData;
    for (( i=1; i<=$NoOfCol; i++ ))
    do
        echo "Enter Field Name: "
        read FName;
        echo $i "Name:"$FName >> $1.metaData;
        echo "Enter Field Datatype: "
        select choice in "Integer" "String"
        do
            case $choice in
                "Integer") echo $i "Datatype:Int"  >> $1.metaData; break ;;
                "String") echo $i "Datatype:String"  >> $1.metaData; break ;;
            esac    
        done
    done
}

function CreateTable
{
    found=0;
    flag=0;
    echo "Enter Name of Table: ";
    read TName;
    while [ $flag = 0 ]
    do 
        for i in `ls`
        do 
            if [ $i = $TName ]
            then 
                found=1;
                break;
            else
                found=0;
            fi
        done

        if [ $found = 1 ]
        then 
            echo $TName "is already Exist... Please Re-enter Name of Table: "
            read TName;
            flag=0;
        else
            touch $TName.data;
            flag=1;
            TableMetaData $TName
            echo $TName "Table Created Successfully...";
        fi
    done    
}

#----> function to Insert into Table <----#
function InsertData
{
    echo "--------------------- $1 Table ---------------------"
    #NoOfCol=`grep "NumberOfCols" $1.metaData | cut -d: -f2`
    NoOfCol=`sed -n '/:/ s/NumberOfCols://p' $1.metaData`
    echo $NoOfCol
    declare -a fieldsNames[$NoOfCol];
    declare -a fieldsDatatypes[$NoOfCol];
    NewRecord="";
    for (( i=1; i<=$NoOfCol; i++ ))
    do
        fieldsNames[$i]=`grep "$i Name" $1.metaData | cut -d: -f2`
        fieldsDatatypes[$i]=`grep "$i Datatype" $1.metaData | cut -d: -f2`
    done

    for (( i=1; i<=$NoOfCol; i++ ))
    do
        #echo $i "----->" $NoOfCol
        echo ${fieldsTypes[$i]}
        echo "Enter "${fieldsNames[$i]}" :"
        read data;
        flag=0;
        while [ $flag = 0 ]
        do
            case $data in 
                +([[:lower:]]|[[:upper:]])) datatype="String" ;;
                +([0-9])) datatype="Int" ;;
                +([[:lower:]]|[[:upper:]]|[0-9])) echo "Invalid Input... Please Re-enter your Data:"
                                                  read data ;;
                *) echo "Invalid Input... Please Re-enter your Data:"
                                                  read data ;;
            esac
            #echo ${fieldsNames[$i]} "---->" $datatype
            if [ ${fieldsDatatypes[$i]} != $datatype ]
            then 
                echo "Invalid Input... Please Re-enter your Data:";
                read data;
            else
                if [ $i == $NoOfCol ]
                then
                    NewRecord+=$data;
                else    
                    NewRecord+=$data":";
                fi
                flag=1;
            fi
        done  
    done
    echo "Your Data Inserted Successfully...";
    echo $NewRecord >> $1.data;
}

function DeleteData
{
    echo "Delete"
}

function SearchOfTable
{
    found=0;
    flag=0;
    echo "Enter Name of Table";
    read TName;
    tName=$TName.data
    echo $tName
    while [ $flag = 0 ]
    do 
        for i in `ls`
        do
            if [ $i = $tName ]
            then 
                found=1;
                break;
            else
                found=0;
            fi
        done

        if [ $found = 1 ]
        then 
            flag=1;
            if [ $1 = "I" ]
            then 
                InsertData $TName
            elif [ $1 = "D" ]
            then
                DeleteData $TName
            fi
        else 
            flag=0;
            echo $TName "Not found.. Please Re-enter the Table Name: ";
            read TName;
        fi            
    done
}

function TableMenu
{
    select choice in "Display Tables" "Create Table" "Insert in Table" "Delete from Table" "Select from Table" "Exit"
    do
        case $choice in
            "Display Tables") DisplayTables ;;
            "Create Table") CreateTable ;;
            "Insert in Table") SearchOfTable "I" ;;
            "Delete from Table") SearchOfTable "D" ;; 
            "Select from Table") ;;
            "Exit") cd ..
                    cd .. 
                    DatabaseMenu ;;
        esac
    done       
}

function DatabaseMenu
{
    echo "------------ Welcome in Nahla & Dalia Database Managment System ------------";
    select choice in "Display All Dalabases" "Create New Database" "Connect on Database" "Exit"
    do 
        case $choice in 
            "Display All Dalabases") DisplayDatabases ;;
            "Create New Database") CreateDatabase ;;
            "Connect on Database") ConnectToDatabase ;;
            "Exit") exit ;;
        esac
    done
    
}

DatabaseMenu
